[package]
name = "advent_18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_lib = { version = "0.1.0", path = "../advent_lib" }
derive_more = "0.99.17"
itertools = "0.10.5"
nom = "7.1.3"
