[package]
name = "advent_24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_lib = { version = "0.1.0", path = "../advent_lib" }
ndarray = "0.15.6"
yap = "0.11.0"
